In [6]:
# Building a matrix
# np.reshape(*,*,'C') C-like population order (row by row)
# ................F') fortran population order (col by col)
# np.array([list],[list],.....)
import numpy as np
mydata = np.arange(0,20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
np.reshape(mydata,(5,4)) # rows, cols

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [9]:
matrix1 = np.reshape(mydata, (5,4),order='C')

In [10]:
# index to 10
matrix1[2][2]

10

In [11]:
matrix2 = np.reshape(mydata, (5,4),order='F')
matrix2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [12]:
# index to 10 again
matrix2[0][2]

10

In [13]:
# different way to index
print(matrix1[2,2])
print(matrix2[0,2])

10
10


In [14]:
# different way to reshape
mydata.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [15]:
# 
r1 = ["I","am","happy"]
r2 = ["what","a","day"]
r3 = [1,2,3]
[r1,r2,r3]

[['I', 'am', 'happy'], ['what', 'a', 'day'], [1, 2, 3]]

In [16]:
np.array([r1,r2,r3])

array([['I', 'am', 'happy'],
       ['what', 'a', 'day'],
       ['1', '2', '3']], dtype='<U5')

In [17]:
print(np.array([r1,r2,r3]))

[['I' 'am' 'happy']
 ['what' 'a' 'day']
 ['1' '2' '3']]


In [ ]:
# 1,2,3 were changed to string chars
# arrays must be of same type